name: Publish static site via GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and deploy MkDocs static site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: MkDocs setup
        run: pip install mkdocs

      - name: Build
        run: mkdocs build --clean

      - name: Deploy
        run: mkdocs gh-deploy --force
        env:
          CONFIG_FILE: mkdocs.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
